tasks:
  - name: Dependencies & Tests
    init: |
      npm install
      npx playwright install --with-deps
    command: npm run dev

  - name: Playwright Tests
    command: npm run test:e2e

  - name: Supabase Setup
    init: |
      echo 'export PATH="'$(cd node_modules/.bin/ && pwd)':$PATH"' >> ~/.bash_profile
      source ~/.bash_profile
      supabase start
    command: |
      echo "Supabase is running"

  - name: Playwright Tests UI
    command: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npm run test:e2e:ui

ports:
  # Playwright
  - port: 5173
    onOpen: open-preview
    visibility: public
  # Supabase ports
  - port: 54321
    onOpen: ignore
    visibility: public
  - port: 54322
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
