tasks:
  - name: Dependencies & Tests
    init: |
      npm install
      npx playwright install --with-deps
    command: npm run dev

  - name: Playwright Tests
    command: npm run test:e2e

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
