# .gitpod.yml

image:
  file: .gitpod.Dockerfile

tasks:
  - name: install cypress to workspace
    init: |
      npm install
      npx cypress install
      npm run dev
  - name: run chrome tests
    command: |
      gp sync-await
      yes | npx cypress run --browser chrome
  - name: open cypress application
    command: |
      gp sync-done
      yes | npx cypress open
  - name: Supabase Setup
    init: |
      npm install supabase
      supabase init
      supabase start
    command: |
      echo "Supabase is running"

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
  - port: 5173
    onOpen: open-preview
    visibility: public
  - port: 54323
    onOpen: ignore
    visibility: public
  # Supabase ports
  - port: 54321
    onOpen: ignore
    visibility: public
  - port: 54322
    onOpen: ignore
    visibility: public
