name: Playwright Tests
on:
  push:
    branches: [third]
  pull_request:
    branches: [third]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Start Supabase
        run: |
          supabase start
          echo "ANON_KEY=$(supabase status --output json | jq -r '.api.anonKey')" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          VITE_SUPABASE_URL: "http://localhost:54321"
          VITE_SUPABASE_ANON_KEY: ${{ env.ANON_KEY }}
        run: npx playwright test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
